name: Publish package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          registry-url: https://npm.pkg.github.com
          scope: "@aarock"
      - run: npm ci
      - run: npm run build
      - run: npm publish